app/Http/routes.php
        Route::get('Δημιουργία-Τοποθέτησης', ['as' => 'manualCreate', 'uses' => 'PlacementsController@manualCreate']);
        Route::post('Δημιουργία-Τοποθέτησης', ['as' => 'manualCreate', 'uses' => 'PlacementsController@saveManualCreate']);

        Route::get('Δημιουργία-Τοποθέτησης-Με-Νέα-Ειδικότητα', ['as' => 'createWithNewEidikotita', 'uses' => 'PlacementsController@createWithNewEidikotita']);

        Route::get('ΚΑΘΗΓΗΤΗΣ/{teacher_id}/ΟΛΑ-ΤΑ-ΤΟΠΟΘΕΤΗΡΙΑ', ['as'=> 'allPlacements', 'uses'=> 'PlacementsController@allByTeacher']);
        Route::get('ΚΑΘΗΓΗΤΗΣ/{teacher_id}/ΤΟΠΟΘΕΤΗΡΙΑ/{year_name}', ['as'=> 'allPlacementsForYears', 'uses'=> 'PlacementsController@allByTeacher']);
        Route::get('ΚΑΘΗΓΗΤΕΣ/{teacher_first_letter_list}/ΤΟΠΟΘΕΤΗΡΙΑ/{year_name}', ['as'=> 'allPlacementsForYearsByLetter', 'uses'=> 'PlacementsController@allByTeacherByLetter']);
        Route::get('ΚΑΘΗΓΗΤΗΣ/{teacher_id}/ΤΟΠΟΘΕΤΗΣΕΙΣ', ['as'=>'placementsDetails', 'uses' => 'PlacementsController@placementsDetailsOfTeacher']);
        Route::get('ΑΝΑΚΛΗΣΗ-ΤΟΠΟΘΕΤΗΣΗΣ/{placement_id}', ['as' => 'softDelete', 'uses' => 'PlacementsController@softDelete']);
        Route::get('ΕΠΑΝΑΦΟΡΑ-ΤΟΠΟΘΕΤΗΣΗΣ/{placement_id}', ['as' => 'restorePlacement', 'uses' => 'PlacementsController@restorePlacement']);
        Route::post('ΟΡΙΣΤΙΚΗ-ΔΙΑΓΡΑΦΗ', ['as' => 'forceDeletePlacement', 'uses' => 'PlacementsController@postPermanentDelete']);

        Route::get('/teacher/{teacher_id}/τοποθέτηση/{placement_id}', ['as' => 'update', 'uses' => 'PlacementsController@updatePlacement']);
        Route::patch('/teacher/{teacher_id}/τοποθέτηση/{placement_id}', ['as' => 'store', 'uses' => 'PlacementsController@storePlacement']);


        Route::get('jsonSchools/{eidikotita?}', ['as'=>'jsonSch','uses'=>'PlacementsController@jsonSchools']);
        Route::get('jsonAllSchools/{eidikotita?}', ['as'=>'jsonAllSch','uses'=>'PlacementsController@jsonAllSchools']);
        Route::get('jsonAllSchoolsList', ['as'=>'jsonTempSch','uses'=>'PlacementsController@jsonTemporarySchools']);
        Route::get('jsonTeachers/{eidikotita?}', ['as'=>'jsonTeachers','uses'=>'PlacementsController@jsonTeachersOfEidikotita']);
        Route::get('jsonAllTeachers/{eidikotita?}', ['as'=>'jsonAllTeachers','uses'=>'PlacementsController@jsonAllTeachersOfEidikotita']);
        Route::get('jsonAllTeachersOfNewKladoi/{klados_slug}', ['as'=>'jsonAllTeachersOfNewKladoi','uses'=>'PlacementsController@jsonAllTeachersOfNewKladoi']);
        Route::get('jsonAllPlacementsTypes', ['as'=>'jsonAllPlacementsTypes','uses'=>'PlacementsController@jsonAllPlacementsTypes']);
        Route::get('jsonTeachersOfEidikotitaPleonazon/{eidikotita}', ['as'=>'jsonPleonazontes', 'uses' => 'PlacementsController@jsonTeachersOfEidikotitaPleonazon']);
        Route::get('getExcel/{id}', ['as' => 'createExcelPlacements', 'uses' => 'ExcelController@excelPraxiPlacements']);
        Route::get('getExcel2/{id}', ['as' => 'createExcelPlacements2', 'uses' => 'ExcelController@excelPraxiPlacements2']);
        Route::get('/{id?}/{praxiId?}/ΤΟΠΟΘΕΤΗΡΙΟ', ['as' => 'createTopothetirio', 'uses' => 'PlacementsController@createPDF']);
        Route::get('/teacher/{teacher_id}/placement/{praxi_id}', ['as' => 'teacherPlacement', 'uses'=> 'PlacementsController@teacherPlacementByPraxi']);
    });
    Route::resource('placements', 'PlacementsController');
});

Route::group(['prefix'=>'ΠΥΣΔΕ', 'as'=>'Pysde::'], function(){

    Route::group(['prefix' => 'Αποσπάσεις', 'as' => 'Apospaseis::'], function(){
        Route::get('Υπολογισμός-Μορίων', ['as' => 'calculateMoria', 'uses' => 'KenaController@calculateMoria']);
        Route::get('Αυτόματος-Υπολογισμός-Μορίων', ['as'=>'prepareCalculate', 'uses' => 'TeacherController@prepareCalculateApospasis']);
        Route::post('Αυτόματος-Υπολογισμός-Μορίων', ['as'=>'autoCalculate', 'uses' => 'TeacherController@calculateApospasis']);
    });



    Route::group(['prefix'=>'Users', 'as'=>'Users::'], function(){
        Route::get('Σχολικές-Μονάδες', ['as'=>'schools', 'uses'=>'UserController@indexSchools']);
        Route::get('Εκπαιδευτικοί', ['as' => 'teachers', 'uses'=>'UserController@indexTeachers']);
    });

    Route::get('Οργανικά-Κενά-Πλεονάσμτα', ['as' => 'organikaKenaPleonasmta', 'uses' => 'KenaController@editOrganikaKenaPleonasmata']);
    Route::get('Επικαιροποίηση-Σχολείων', ['as'=>'confirmationUsers', 'uses'=>'KenaController@confirmationSchools']);
    Route::get('printDescript', ['as'=>'printDescription', 'uses'=>'KenaController@printDescriptions']);
    Route::resource('user', 'UserController');
    
    Route::group(['prefix'=>'Kena-Pleonasmata', 'as'=>'Kena::'], function(){
        
        Route::get('ΟΛΑ', ['as'=>'all','uses'=>'KenaController@all']);
        Route::get('changeAccess', ['as'=>'changeAccess','uses'=>'KenaController@changeSchoolAccess']);
        
        Route::get('ExcelManagement', ['as'=>'excelManage', 'uses'=>'ExcelController@excelPreparation']);
        Route::get('ExcelArchives', ['as'=>'excelArchive','uses'=>'ExcelController@excelArchives']);
        Route::post('toExcel', ['as'=>'excelConvert','uses'=>'ExcelController@excelCreate']);
        Route::post('toExcelOrganika', ['as'=>'excelConvertOrganiak','uses'=>'ExcelController@excelCreateOrganika']);

        Route::get('toHTML', ['as'=>'toHTML', 'uses' => 'ExcelController@excelHtmlCreate']);

        Route::post('toExcelParallili', ['as'=> 'excelConvertParallili', 'uses'=>'ExcelController@excelParalliliEidiki']);
        Route::post('toExcelEidikis', ['as' => 'excelConvertEidiki', 'uses'=>'ExcelController@createTmimataEdaksis']);
        Route::get('download/{file?}', 'ExcelController@excelDownloadKenaPleonasmata');        
        
        Route::get('view', ['as'=>'view','uses'=>'KenaController@indexView']);
        Route::get('printShowSchool/{school}', ['as'=>'printKena', 'uses'=>'KenaController@printShow']);

        Route::resource('for', 'KenaController');
    });
    
    Route::group(['prefix'=>'Protocol', 'as'=>'Protocol::'], function(){
        Route::get('create',['as'=>'create','uses'=>'ProtocolController@create']);
        Route::post('create', ['as'=>'postCreate','uses'=>'ProtocolController@store']);
        
        Route::get('manual',['as'=>'manual','uses'=>'ProtocolController@manualCreate']);
        Route::post('manual', ['as'=>'postManual','uses'=>'ProtocolController@manualStore']);

        Route::get('edit/{id}', ['as'=>'edit','uses'=>'ProtocolController@edit']);
        Route::patch('edit/{id}', ['as'=>'patch','uses'=>'ProtocolController@update']);

        Route::get('edit-archives/{id}', ['as'=>'edit','uses'=>'ProtocolController@editArchives']);
        Route::patch('edit-archives/{id}', ['as'=>'patch','uses'=>'ProtocolController@updateArchives']);


        Route::get('convertPDF', ['as'=>'convert','uses'=>'ProtocolController@indexPDF']);
        Route::get('protocolToPDF', ['as'=>'toPDF','uses'=>'ProtocolController@viewToPDF']);
        Route::get('protocolArchivesToPDF', ['as'=>'archivesToPDF', 'uses'=>'ProtocolController@viewArchivesToPDF']);
        Route::get('archives', ['as'=>'archives','uses'=>'ProtocolController@indexArchive']);
        Route::get('/', ['as'=>'index','uses'=>'ProtocolController@index']);
    });

    Route::group(['prefix'=>'teachers', 'as'=>'Teachers::'], function(){

        Route::get('Ονομαστικά-Υπεράριθμοι', ['as'=> 'makeOnomastikaYperarithmous', 'uses'=> 'TeacherController@manageOnomastikaYperarithmous']);

        Route::get('check', ['as'=>'allTeachers', 'uses'=>'TeacherController@getTeachersNotConfirmed']);
        Route::get('allForChecking', ['as' => 'allTeachersForChecking', 'uses' => 'TeacherController@getAllTeachersForConfirmation']);

        Route::get('requests', ['as'=>'allRequests', 'uses'=>'TeacherController@allRequests']);
        Route::get('archives', ['as'=>'archives', 'uses'=>'TeacherController@archivesTeachersRequests']);
        Route::get('checkProfile/teacher/{id}' , ['as'=>'check', 'uses'=>'TeacherController@checkProfile']);
        Route::patch('confirmProfile/{id}', ['as'=>'confirm', 'uses'=>'TeacherController@confirmTeacherProfile']);
        Route::get('reCheckProfile/{id}', ['as'=>'recheck', 'uses'=>'TeacherController@wrongTeacherProfile']);
        Route::patch('checkProfile/{id}', ['as'=>'updateTeacherProfile', 'uses'=>'TeacherController@updateProfileFields']);
        Route::get('{id}/action/giveProtocol', ['as'=>'giveProtocol', 'uses' => 'TeacherController@giveProtocol']);
        Route::get('{teacherName}/{id}/download', ['as'=>'downloadPDF', 'uses'=> 'TeacherController@downloadPDF']);
        Route::get('Διαχείριση-Αιτήσεων', ['as'=>'manageRequests', 'uses'=>'TeacherController@getManage']);
        Route::get('ΞΕΚΛΕΙΔΩΜΑ-ΠΡΟΦΙΛ/{id}', ['as' => 'unlockProfile', 'uses'=>'TeacherController@unlock']);
        Route::get('ΚΑΜΙΑ-ΑΛΛΑΓΗ-ΣΤΟ-ΠΡΟΦΙΛ/{id}', ['as' => 'lockProfile', 'uses'=>'TeacherController@lock']);

        Route::get('{id}/ΑΚΥΡΩΣΗ-ΑΙΤΗΜΑΤΟΣ', ['as'=> 'cancelRequest', 'uses' => 'TeacherController@cancelRequest']);
        Route::get('{id}/ΕΠΙΒΕΒΑΙΩΣΗ-ΑΙΤΗΜΑΤΟΣ', ['as'=> 'confirmRequest', 'uses' => 'TeacherController@confirmRequest']);

        Route::get('Μεταμόρφωση-Αιτήσεων', ['as' => 'prepareExcel', 'uses' => 'ExcelController@excelRequestPreparation']);
        Route::post('downloadExcel', ['as'=>'downloadExcelTeachersRequest', 'uses' => 'ExcelController@excelTeachersRequests']);
        Route::get('displayExcel', ['as'=>'displayExcelTeachersRequest', 'uses' => 'ExcelController@displayExcelTeachersRequests']);
    });
    
});

Route::get('kena-pleonasmata/toPDFsch', 'KenaController@pdfOrderBySchools');

Route::group(['prefix'=>'user', 'as'=>'User::'], function(){
    Route::get('info', ['as'=>'getInfo', 'uses'=> 'ProfileController@getInfo']);
    Route::post('info', ['as'=>'postInfo', 'uses'=> 'ProfileController@postInfo']);

app/Monimos.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Monimos extends Model
{
    protected $table = 'monimoi';

    protected $fillable = [
        'am',
        'organiki',
        'moria',
        'orario',
        'county',
        'moria_apospasis',
        'dieuthinsi'
    ];

    public function teacher()
    {
        return $this->morphOne(\App\Teacher::class, 'teacherable');
    }

    public function getOrganikiNameAttribute()
    {
        $school = School::find($this->organiki);

        if($school == null){
                                                                //MUST CHANGE WITH A LOOP FROM REQUESTS FILE CONFIG
            if ($this->organiki == 1000){
                return 'ΔΙΑΘΕΣΗ ΠΥΣΔΕ';
            }elseif ($this->organiki == 2000){
                return 'Απόσπαση από Δ.Δ.Ε. '.\Config::get('requests.county')[$this->county];
            }elseif ($this->organiki == 3000){
                return 'Αναπληρωτής';
            }elseif ($this->organiki == 4000) {
                return 'Απόσπαση από Π/θμια';
            }
        }else {
                return $school->name;
            }
    }

    public function getOrganikiSlugAttribute()
    {
        $school = School::find($this->organiki);

        if($school == null){
            if ($this->organiki == 1000){
                return 'ΔΙΑΘΕΣΗ ΠΥΣΔΕ';
            }elseif ($this->organiki == 2000){
                return 'Δ.Δ.Ε. '.\Config::get('requests.county')[$this->county];
            }elseif ($this->organiki == 4000){
                return 'Διεύθυνση Π';
            }
        }else{
            return $school->name . ' (οργανική)';
        }
    }

    public function getGroupNameAttribute()
    {
        $school = School::find($this->organiki);

        if ($school != null){
            return $school->group;
        }
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Carbon\Carbon;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'role_id',
        'userable_id',
        'userable_type',
        'provider',
        'provider_id',
        'login_at',
        'sex',
        'second_mail'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
    
    protected $dates = ['login_at'];
    

    public function notifications()
    {
        if ($this->role->slug == 'pysde_secretary'){
            return Notification::where('forRole', 'pysde_secretary')
                ->where('unread', 'is_true')
                ->orWhere(function($query){
                    $query->where('forRole','=','self')
                        ->where('user_id','=',$this->id);
                })
                ->get()->sortByDesc('created_at');
        }elseif($this->role->slug == 'ofa'){
            return Notification::where('forRole', 'ofa')
                ->where('unread', 'is_true')
                ->get()->sortByDesc('created_at');
        }else{
            return Notification::where(function($query){
                $query->where('forRole','=',$this->role->slug)
                    ->where('forUser', '=', $this->id);
            })
                ->where('unread', '=', 'is_true')
                ->orWhere('forRole', $this->role->slug.'s')
                ->orWhere(function($query){
                    $query->where('forRole','=','self')
                        ->where('user_id','=',$this->id);
                })
                ->get()->sortByDesc('created_at');
        }
    }


    public function readedNotifications()
    {
        if ($this->role->slug == 'pysde_secretary'){
            return Notification::where('forRole', 'pysde_secretary')
                ->where('unread', 'is_false')
                ->orWhere(function($query){
                    $query->where('forRole','=','self')
                        ->where('user_id','=',$this->id);
                })
                ->get()->sortByDesc('created_at');
        }elseif($this->role->slug == 'ofa') {
            return Notification::where('forRole', 'ofa')
                ->where('unread', 'is_false')
                ->get()->sortByDesc('created_at');
        }else{
            return Notification::where(function($query){
                $query->where('forRole','=',$this->role->slug)
                    ->where('forUser', '=', $this->id);
            })
                ->where('unread', '=', 'is_false')
                ->orWhere('forRole', $this->role->slug.'s')
                ->orWhere(function($query){
                    $query->where('forRole','=','self')
                        ->where('user_id','=',$this->id);
                })
                ->get()->sortByDesc('created_at');
        }
    }
    
    public function role(){
        return $this->belongsTo(\App\Role::class,'role_id', 'id');
    }

    public function isRole($role){
        if (is_string($role)){
            if ($this->role->slug == $role){
                return true;
            }   
            return false;
        }
        
        foreach($role as $r){
            if ($this->isRole($r->slug)){
                return true;
            }
        }
        
        return false;
    }
    
    public function userable()
    {
        return $this->morphTo();
    }
    
    
    public function getFullNameAttribute(){
        return $this->last_name .' '. $this->first_name;
    }

    public function getLoginAtAttribute($date)
    {
        return Carbon::parse($date)->format('d/m/Y');
    }


}

resources/views/pysde/moria/autocalculate.blade.php
@extends('app')

@section('title')
    Αυτόματος Υπολογισμός Μορίων Αποσπάσεων
@stop

@section('header.style')
    <link href="https://cdn.datatables.net/1.10.9/css/dataTables.bootstrap.min.css" rel="stylesheet">
@endsection

@section('loader')
    @include('loader')
@endsection

@section('content')
    <h1 class="page-heading">Καθηγητές που είναι σε διαδικασία απόσπασης</h1>

    @if($requests->isEmpty())
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <hr>
                    <div class="alert alert-info text-center" role="alert">Δεν υπάρχει καθηγητής που έχει ζητήσει απόσπαση</div>
                </div>
            </div>
        </div>
    @else
        <div class="col-md-12 text-center">
            {!! Form::open(['id'=>'aitisiForm']) !!}
                {!! Form::submit('Υπολογισμός Μορίων',['class'=> 'btn btn-primary btn-lg' ,'id'=>'submitCalculate']) !!}
            {!! Form::close() !!}
        </div>

        <table id="requests" class="table table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
                <tr class="active">
                    <th>Αρ. Μητρώου</th>
                    <th>Ονοματεπώνυμο</th>
                    <th>Πατρώνυμο</th>
                    <th>Ειδικότητα</th>
                    <th>Οργανική</th>
                    <th>Μόρια Απόσπασης</th>
                </tr>
            </thead>

            <tbody>
                @foreach($requests as $request)
                    <tr>
                        <td>{!! $request->teacher->teacherable->am !!}</td>
                        <td>{!! $request->teacher->user->full_name !!}</td>
                        <td>{!! $request->teacher->middle_name !!}</td>
                        <td>{!! $request->teacher->klados_name !!}</td>
                        <td>{!! $request->teacher->teacherable->organiki_name !!}</td>
                        <td>{!! $request->teacher->teacherable->moria_apospasis !!}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

@stop

@section('scripts.footer')
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {

        $('#submitCalculate').on('click', function(e){
            e.preventDefault();
            $('#loader').removeClass('invisible')
                .addClass('loading');
            setTimeout(function(){
                $('#aitisiForm').submit();
            }, 6000);
        });

            var table = $('#requests').DataTable({
                    "order": [[ 1, "asc" ]],
                    "pageLength": 50,
                    "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 2 ] } ],
                    "language": {
                                "lengthMenu": "Προβολή _MENU_ εγγραφών ανά σελίδα",
                                "zeroRecords": "Δεν βρέθηκε καμία εγγραφή",
                                "info": "Προβολή σελίδας _PAGE_ από _PAGES_",
                                "infoEmpty": "Καμία εγγραφή διαθέσιμη",
                                "infoFiltered": "(φιλτράρισμα  από  _MAX_ συνολικές εγγραφές)",
                                "search": "Αναζήτηση:",
                                "paginate": {
                                      "previous": "Προηγούμενη",
                                      "next" : "Επόμενη"
                                    }
                            }
            });
        });
    </script>
@endsection

resources/views/pysde/moria/moria_apospasis.blade.php
@extends('app')

@section('title')
    Υπολογισμός Μορίων Απόσπασης
@stop

@section('header.style')

    <style>
            [v-cloak] {
              display: none;
            }
    </style>

@endsection

@section('content')

        <h1 class="page-heading">Υπολογισμός μορίων απόσπασης</h1>

        <div class="container" id="app">
            <div class="row">
                <div class="col-md-2"></div>
                <div class="col-md-4">
                    <div class="form-group form-inline">
                        <label>Χρόνια:</label>
                        <input type="text" size="2" maxlength="2" v-model="years">
                        <label>Μήνες:</label>
                        <input type="text" size="2" maxlength="2" v-model="months">
                        <label>Ημέρες:</label>
                        <input type="text" size="2" maxlength="2" v-model="days">
                    </div>

                    <div class="form-group form-inline">
                        <label>Συνυπηρέτηση:</label>
                        <select v-model="sinipiretisi">
                            <option value="0">ΟΧΙ</option>
                            <option value="1">ΝΑΙ</option>
                        </select>

                        <label>Εντοπιότητα:</label>
                        <select v-model="entopiotita">
                            <option value="0">ΟΧΙ</option>
                            <option value="1">ΝΑΙ</option>
                        </select>
                    </div>

                    <div class="form-group">
                        <label>Οικογενειακοί Λόγοι:</label>
                        <select v-model="family">
                            @foreach(Config::get('requests.family_situation') as $k=>$v)
                                <option value="{!! $k !!}">
                                    {!! $v !!}
                                </option>
                            @endforeach
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="kids">Αρ. Παιδιών:</label>
                        <input id="kids" type="text" size="2" maxlength="2" v-model="kids">
                    </div>

                    <div class="form-group checkbox">
                        <label for="sovaroi" class="control-label">
                            <input @click="changeSovaroi" type="checkbox" id="sovaroi" v-model="sovaroi">
                            Σοβαροί Λόγοι Υγείας;
                        </label>
                    </div>

                    <div v-cloak v-if="sovaroi">
                        <div class="form-group">
                            <label>Λόγοι Υγείας Ιδίου:</label>
                            <select v-model="idiou">
                                @foreach(Config::get('requests.logoi_ygeias.idiou.data') as $k=>$v)
                                    <option value="{!! $k !!}">
                                        {!! $v !!}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Λόγοι Υγείας Συζύγου:</label>
                            <select v-model="sizigou">
                                @foreach(Config::get('requests.logoi_ygeias.sizigou.data') as $k=>$v)
                                    <option value="{!! $k !!}">
                                        {!! $v !!}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Λόγοι Υγείας Παιδιών:</label>
                            <select v-model="paidion">
                                @foreach(Config::get('requests.logoi_ygeias.paidiou.data') as $k=>$v)
                                    <option value="{!! $k !!}">
                                        {!! $v !!}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Λόγοι Υγείας Γονέων:</label>
                            <select v-model="goneon">
                                @foreach(Config::get('requests.logoi_ygeias.goneon.data') as $k=>$v)
                                    <option value="{!! $k !!}">
                                        {!! $v !!}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Λόγοι Υγείας Αδερφών:</label>
                            <select v-model="aderfon">
                                @foreach(Config::get('requests.logoi_ygeias.aderfon.data') as $k=>$v)
                                    <option value="{!! $k !!}">
                                        {!! $v !!}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Εξωσωματική:</label>
                            <select  v-model="exosomatiki">
                                @foreach(Config::get('requests.logoi_ygeias.exosomatiki.data') as $k=>$v)
                                    <option value="{!! $k !!}">
                                        {!! $v !!}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>


                </div>
                <div class="col-md-4 text-center" style="vertical-align: middle">
                    <label>Σύνολο Μορίων : <span v-cloak style="color: blue"><h1>@{{ calculator }}</h1></span> </label>
                </div>
                <div class="col-md-2"></div>
            </div>

        </div>

@stop

@section('scripts.footer')
        <script src="/js/moria.js"></script>
@endsection