app/Http/routes.php
//        return redirect()->route('User::getProfile');
//    }
//}]);

Route::post('aj/yperarithmos/fetchSelectedSchoolsYperarithmon', ['as' => 'fetchSelectedSchoolsYperarithmon', 'uses' => 'RequestController@ajaxFetchSchoolsYperarithmou']);


Route::get('lost-password', ['as'=>'getLostPassword', 'uses'=>'Auth\LostController@getEmail']);
Route::post('lost-password', ['as'=>'postLostPassword', 'uses'=>'Auth\LostController@postEmail']);
Route::get('password/reset/{token?}', ['as'=>'getResetLostPassword','uses'=>'Auth\LostController@getReset']);
Route::post('password/reset', ['as'=>'postResetLostPassword', 'uses'=>'Auth\LostController@postReset']);

Route::post('aj/organikes/saveRequest', ['as' => 'saveOrganikaRequest', 'uses' => 'RequestController@ajaxSaveOrganikaRequest']);
Route::post('aj/organikes/saveRequestVeltiwsi', ['as' => 'saveOrganikaRequestVeltiwsi', 'uses' => 'RequestController@ajaxSaveOrganikaRequestVeltiwsi']);
Route::post('aj/organikes/sentRequestForProtocol', ['as' => 'sentOrganikaRequestForProtocol', 'uses' => 'RequestController@ajaxSentOrganikaRequestForProtocol']);
Route::post('aj/organikes/sentRequestForProtocolVeltiwsi', ['as' => 'sentOrganikaRequestForProtocolVeltiwsi', 'uses' => 'RequestController@ajaxSentOrganikaRequestForProtocolVeltiwsi']);
Route::post('aj/organikes/permanentlyDelete', ['as' => 'permanentlyDelete', 'uses' => 'RequestController@ajaxPermanentlyDeleteRequestOrganika']);
Route::get('aj/organikes/fetchSelectedSchools', ['as' => 'fetchSelectedSchoolsOrganika', 'uses' => 'RequestController@ajaxFetchSchools']);
Route::get('aj/organikes/fetchSelectedSchoolsVeltiwsi', ['as' => 'fetchSelectedSchoolsOrganikaVeltiwsi', 'uses' => 'RequestController@ajaxFetchSchoolsVeltiwsi']);
Route::post('aj/organika/teachersSchoolFromMySchool', ['as' => 'fetchTeachersFromMySchool', 'uses' => 'TeacherController@ajaxFetchTeachersFromMySchool']);
Route::post('aj/organika/toggleYperarithmiaValueOfTeacher', ['as' => 'toggleYperarithmiaValueOfTeacher', 'uses' => 'TeacherController@ajaxToggleYperarithmiaValueOfTeacher']);

Route::post('aj/yperarithmia/save', ['as' => 'storeYperarithmia', 'uses' => 'RequestController@ajaxCreateYperarithmia']);
Route::get('aj/organika/schools', ['as' => 'editOrganika', 'uses' => 'KenaController@getOrganikaKenaSchools']);
Route::get('aj/organika_yperarithmon/schools', ['as' => 'getOrganikaYperarithmon', 'uses' => 'KenaController@getOrganikaKenaYperarithmonSchools']);

Route::post('aj/organika/eidikotitesWithKenaPleonasmata', ['as' => 'getEidikotites', 'uses' => 'KenaController@postEidikotitesForSchool']);
Route::post('aj/organika/saveEidikotaToSchool', ['as' => 'saveEidikotita', 'uses' => 'KenaController@saveEidikotitaForSchool']);

Route::post('aj/at/save', ['as'=>'store', 'uses'=>'RequestController@store']);
Route::post('aj/at/update/{id}', ['as'=>'updateRequestTeacher', 'uses'=>'RequestController@update']);
Route::get('aj/at/edit/{id}', ['as'=>'ajaxEditAitisi', 'uses'=>'RequestController@ajaxEdit']);
Route::post('aj/at/delete/{id}/{type}', ['as'=>'deleteRowRequest', 'uses'=>'RequestController@deleteRowRequest']);

Route::post('aj/at/chPrm', ['as'=>'changePermission', 'uses'=>'TeacherController@changeTeacherRequestAccess']);

Route::get('aj/protocols', ['as'=>'ajaxProtocols', 'uses'=>'ProtocolController@ajaxIndex']);

Route::get('aj/no/de', ['as'=> 'ajaxDeleteNotifications', 'uses' => 'NotificationController@ajaxDeleteAll']);

Route::get('aj/schools/index', ['as'=> 'ajaxIndexSchools', 'uses'=> 'UserController@ajaxIndex']);

Route::get('aj/schools/modalData', ['as'=> 'ajaxSchoolModalData', 'uses'=> 'UserController@ajaxModalData']);
Route::post('aj/schools/modalDataSave', ['as'=> 'ajaxSchoolModalDataSave', 'uses'=> 'UserController@ajaxSaveSchoolModalDetails']);

Route::get('aj/teachers/modalData', ['as'=> 'ajaxTeacherModalData', 'uses'=> 'UserController@ajaxTeacherModalData']);
Route::post('aj/teachers/modalDataSave', ['as'=> 'ajaxTeacherModalDataSave', 'uses'=> 'UserController@ajaxSaveTeacherModalDetails']);
Route::post('aj/teachers/modalDataLittleSave', ['as'=> 'ajaxTeacherModalLittleDataSave', 'uses'=> 'UserController@ajaxSaveTeacherModalLittleDetails']);

Route::get('aj/teachers/modalChangeProfile', ['as' => 'ajaxTeacherModalChangeProfileRequest', 'uses' => 'ProfileController@ajaxRequestChangeProfile']);
Route::get('aj/teachers/modalChangeMisthodosia', ['as' => 'ajaxTeacherModalChangeMisthodosiaRequest', 'uses' => 'MisthodosiaController@ajaxRequestChangeMisthodosia']);
Route::get('aj/teachers/modalChangeMisthodosia', ['as' => 'ajaxTeacherModalChangeMisthodosiaRequest', 'uses' => 'MisthodosiaController@ajaxRequestChangeMisthodosia']);

Route::post('aj/placements/savePlacementWithNewEidikotita', ['as' => 'saveWithNewEidikotita', 'uses' => 'PlacementsController@saveWithNewEidikotita']);


Route::get('redis', function(){
    event(new \App\Events\TestEvent('nicsmyrn'));
    return 'done';
});

Route::get('redis_view', function(){
    return view('redis');
});


Route::get('notifications', 'NotificationController@index');

Route::get('dropbox', 'UserController@testDropbox');

Route::get('666', function(){
    return view('teacher.placements.666');
});
Route::get('hidden/{filename}', function($filename){
    //$2y$10$M7lTqmCckaPkU0uEd87RpulMkrDY95L2V8onvVodtDfxtQr24vUCG.jpg
    $path = storage_path() . '/app/' . $filename;

    if(!File::exists($path)) abort(404);

    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

Route::get('aj/notifications/fetchNotifications', ['as' => 'fetchNotifications', 'uses' => 'NotificationController@fetchNotifications']);
Route::get('aj/notifications/getUserId', ['as' => 'getUserId', 'uses' => 'NotificationController@getUserId']);




/*
 * **********************   K T E L  S T A R T  ******************
 */

Route::get('απουσιολόγιο', function(){
    return view('KTEL.schools.modal-test');
});


Route::group(['prefix'=>'ΚΤΕΛ', 'as'=>'BUS::'], function() {

    Route::group(['prefix' => 'ΔΙΑΧΕΙΡΙΣΗ', 'as' => 'Admin::'], function () {
        Route::get('δρομολόγια', ['as' => 'routes', 'uses' => 'KTEL\AdminKtelController@routesAdmin']);
        Route::get('περίοδος', ['as' => 'period', 'uses' => 'KTEL\AdminKtelController@managePeriod']);
        Route::get('στατιστικά', ['as' => 'statistics', 'uses' => 'KTEL\AdminKtelController@statistics']);
    });

    Route::group(['prefix' => 'ΣΧΟΛΕΙΟ', 'as' => 'School::'], function () {
        Route::get('επιλογή-δρομολογίων', ['as' => 'chooseRoutes', 'uses' => 'KTEL\SchoolKtelController@chooseRoutes']);
        Route::post('επιλογή-δρομολογίων', ['as' => 'postChosenRoutes', 'uses' => 'KTEL\SchoolKtelController@postChosenRoutes']);
        Route::get('διαχείριση-δρομολογίων',['as' => 'editPeriods', 'uses' => 'KTEL\SchoolKtelController@editRoutePeriods']);
        Route::get('ΒΕΒΑΙΩΣΗ-ΜΕΤΑΦΕΡΟΜΕΝΩΝ-ΜΑΘΗΤΩΝ/{year}/{month}', ['as'=> 'viewPDF', 'uses'=> 'KTEL\SchoolKtelController@showPDFperiodRoute']);
        Route::get('Λίστα-Βεβαιώσεων', ['as' => 'listPdf', 'uses' => 'KTEL\SchoolKtelController@listPdf']);
        Route::get('download/{file}', ['as'=>'downloadPDF', 'uses'=>'KTEL\SchoolKtelController@downloadPDF']);
    });
});


Route::group(['prefix'=>'ajax', 'as'=>'ajax::'], function(){
    /*
     * AJAX REQUESTS FOR SCHOOLS
     */
    Route::get('/ktel/getAbsences/{periodRoute}', ['as'=>'getAbsences', 'uses' => 'KTEL\AjaxKtelSchoolController@getSpecificAbsences']);
    Route::post('/ktel/updateAbsences', ['as'=>'updateAbsences', 'uses' => 'KTEL\AjaxKtelSchoolController@updateAbsences']);
    Route::post('/ktel/insertAbsences', ['as'=>'insertAbsences', 'uses' => 'KTEL\AjaxKtelSchoolController@insertAbsences']);
    Route::get('/ktel/existingroutes', ['as' => 'getBusRoute', 'uses' => 'KTEL\AjaxKtelSchoolController@getExistingRoutes']);
    Route::get('/ktel/existingroutesEnabled', ['as' => 'getBusRouteEnabled', 'uses' => 'KTEL\AjaxKtelSchoolController@getExistingRoutes_ENABLED']);
    Route::get('/ktel/getPeriodRoutes/{periodId}', ['as' => 'getPeriodRoutes', 'uses' => 'KTEL\AjaxKtelSchoolController@getPeriodRoutes']);
    Route::get('/ktel/getYears', ['as'=>'getYears', 'uses' => 'KTEL\AjaxKtelSchoolController@getAllYears']);
    Route::get('/ktel/school/municipalities', ['as' => 'allSchoolMunicipalities', 'uses' => 'KTEL\AjaxKtelSchoolController@allMunicipalities']);
    Route::get('/ktel/school/busroutes/{m_id}', ['as' => 'getSchoolBusRoute', 'uses' => 'KTEL\AjaxKtelSchoolController@getBusRoute']);
    Route::post('/ktel/insertPeriodRoutes', ['as' => 'insertPeriods', 'uses' => 'KTEL\AjaxKtelSchoolController@insertPeriodRoutes']);
    Route::post('/ktel/updatePeriodRoutes', ['as' => 'updatePeriodRoutes', 'uses' => 'KTEL\AjaxKtelSchoolController@updatePeriodRoutes']);

    /*
     *  AJAX REQUESTS FOR KTEL ADMIN
     */
    Route::post('/ktel/changePermission', ['as'=>'changePermission', 'uses' => 'KTEL\AjaxKtelDdeController@changePermission']);

    Route::get('/ktel/getPeriodCollection', ['as'=>'getPeriodCollection', 'uses' => 'KTEL\AjaxKtelDdeController@getPeriodCollection']);
    Route::delete('ktel/busroutes/{route}', ['as' => 'deleteRoute', 'uses' => 'KTEL\AjaxKtelDdeController@deleteRoute']);
    Route::get('/ktel/routetypes', ['as' => 'getRouteTypes', 'uses' => 'KTEL\AjaxKtelDdeController@getRouteTypes']);
    Route::get('/ktel/municipalities', ['as' => 'allMunicipalities', 'uses' => 'KTEL\AjaxKtelDdeController@allMunicipalities']);
    Route::get('/ktel/busroutes/{m_id}', ['as' => 'getBusRoute', 'uses' => 'KTEL\AjaxKtelDdeController@getBusRoute']);  //22222222222
    Route::post('/ktel/busroutes', ['as' => 'updateBusRoute', 'uses' => 'KTEL\AjaxKtelDdeController@updateBusRoute']);
    Route::post('/ktel/addroute', ['as' => 'addRoute', 'uses' => 'KTEL\AjaxKtelDdeController@addRoute']);
});
/*
 * **********************   K T E L  E N D  ******************
 */


/*

app/Notification.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Notification extends Model
{
    //
    protected $table = 'notifications';

    protected $fillable = [
        'user_id',
        'title',
        'description',
        'type',
        'url',
        'unread',
        'forRole',
        'forUser',
        'uniqueAction'
    ];

    protected $appends = [
        'hour_time',
        'minute_time',
        'time'
    ];

    public function user()
    {
        return $this->belongsTo('App\User','user_id', 'id');
    }

    public function getTimestampAttribute()
    {
        return Carbon::parse($this->created_at)->format('d/m/Y και ώρα H:i:s');
    }

    public function getHourTimeAttribute()
    {
        return Carbon::parse($this->created_at)->format('H');
    }

    public function getMinuteTimeAttribute()
    {
        return Carbon::parse($this->created_at)->format('i');
    }

    public function getTimeAttribute()
    {
        return Carbon::parse($this->created_at)->toIso8601String();
    }
}

app/Http/Controllers/NotificationController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Request;
use App\Notification;

class NotificationController extends Controller
{
    private $user;

    public function __construct()
    {
        $this->middleware('auth');
        $this->user = \Auth::user();
    }

    public function index()
    {
        $this->resetNotifications();

        $notifications = $this->user->readedNotifications();
        return view('partials.nav.notifications.index', compact('notifications'));
    }

    public function ajaxDeleteAll()
    {
        if (\Request::ajax()){
            $this->deleteAllNotifications();
            flash()->success('','ΟΛΕΣ οι ειδοποιήσεις ΔΙΑΓΡΑΦΗΚΑΝ');
            return 'true';
        }else{
            abort(404);
        }
    }

    public function getUserId()
    {
        if(\Request::ajax()){
            return $this->user->id;
        }else{
            abort(404);
        }
    }

    public function fetchNotifications()
    {
        if(\Request::ajax()){
            return $this->user->notifications()->values();
        }else{
            abort(404);
        }
    }

    private function deleteAllNotifications()
    {
        if($this->user->isRole('ofa')){
            return Notification::where('forRole', $this->user->role->slug)
                ->delete();
        }else{
            return Notification::where('forRole', $this->user->role->slug)
                ->where('forUser', $this->user->id)
                ->delete();
        }
    }

    private function resetNotifications()
    {
        return Notification::where('forRole', $this->user->role->slug)
            ->where('unread', 'is_true')
            ->orWhere(function($query){
                $query->where('forRole','=','self')
                    ->where('user_id','=',$this->user->id);
            })
            ->update([
                'unread' => 'is_false'
            ]);
    }



}

resources/views/partials/nav/notifications/for_misthodosia.blade.php
    socket.on('misthodosia:App\\Events\\TeacherChangeMisthodosiaNotification', function(data){
        addNotification(data.url,data.type, data.title, data.description);
    });


    socket.on('misthodosia:App\\Events\\TeacherSentNewMisthodosiaDetails', function(data){
        addNotification(data.url,data.type, data.title, data.description);
    });

resources/views/partials/nav/notifications/for_pysde.blade.php
    socket.on('pysde_secretary:App\\Events\\SchoolSaveChanges', function(data){
        console.log(data);
        addNotification(data.url,data.type, data.title, data.description);
    });
    socket.on('pysde_secretary:App\\Events\\TeacherSendNotificationToPysde', function(data){
        console.log(data);
        addNotification(data.url,data.type, data.title, data.description);
    });

    socket.on('pysde_secretary:App\\Events\\SchoolConfirmToPysde', function(data){
        console.log(data);
        addNotification(data.url,data.type, data.title, data.description);
    });

    socket.on('pysde_secretary:App\\Events\\TeacherChangeProfileNotification', function(data){
        console.log(data);
        addNotification(data.url,data.type, data.title, data.description);
    });

resources/views/partials/nav/notifications/for_school.blade.php
var permissionLabel = $('#schools_read_only');


@can('edit_school_kena')
    permissionLabel.detach();
@endcannot

socket.on('school-permission:App\\Events\\SchoolGrantEditPermission', function(data){
    if(data.noPermission){
        permissionLabel.appendTo('#navbar_menu');
    }else{
        permissionLabel.detach();
    }
});

socket.on('school-{!! Auth::id() !!}:App\\Events\\PysdeSendNotificationToSchool', function(data){
   addNotification(data.url,data.type, data.title, data.description);
});

resources/views/partials/nav/notifications/for_teacher.blade.php
    socket.on('user-{!! Auth::id() !!}:App\\Events\\PysdeSendNotificationToTeacher', function(data){
       addNotification(data.url,data.type, data.title, data.description);
    });


    socket.on('user-{!! Auth::id() !!}:App\\Events\\MisthodosiaSendNotificationToTeacher', function(data){
       addNotification(data.url,data.type, data.title, data.description);
    });

resources/views/partials/nav/notifications/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>
            <div class="col-md-6">
                    <h1 class="page-heading">Ειδοποιήσεις</h1>
            </div>
            <div class="col-md-3">
                @if(!$notifications->isEmpty())
                    <button id="deleteAllNotifications" class="btn btn-danger btn-lg"><i class="glyphicon glyphicon-trash"></i> Διαγραφή</button>
                @endif
            </div>
        </div>

        <div class="col-md-10 col-md-offset-1">
            @if(!$notifications->isEmpty())
                <table class="table table-hover">
                    <thead>
                        <th>Τίτλος</th>
                        <th>Ημερομηνία & ώρα</th>
                        <th>Περιγραφή</th>
                    </thead>
                    <tbody>
                        @foreach($notifications as $notification)
                            <tr class="{!! $notification->type !!} clickable-row" data-href="{!! $notification->url !!}?action={!! $notification->action !!}">
                                <td>{!! $notification->title !!}</td>
                                <td>{!! $notification->timestamp !!}</td>
                                <td>{!! $notification->description !!}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                <div class="alert alert-warning text-center" role="alert"><h3><b>Δεν υπάρχουν ειδοποιήσεις</b></h3></div>
            @endif
        </div>
    </div>
@endsection

@section('scripts.footer')
    <script>
        jQuery(document).ready(function($) {
            $(".clickable-row").click(function() {
                window.document.location = $(this).data("href");
            })
            .on('mouseover', function(){
                $(this).css('cursor', 'pointer');
            });

            $('#deleteAllNotifications').on('click', swalAlertDelete)
        });

        function swalAlertDelete(e){
            e.preventDefault();

            swal({
                title: "Προσοχή!",
                text: "Με αυτήν την ενέργεια θα διαγραφούν ΟΛΕΣ οι ειδοποιήσεις",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Εντάξει",
                cancelButtonText: "Άκυρο",
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
                closeOnCancel: true },
                function(){
                    $.ajax({
                        type : 'get',
                        url : "{!! route('ajaxDeleteNotifications')!!}",
                        success : function(data){
                            location.reload(true);
                        },
                        error: function (request, status, error) {
                           $('body').html(request.responseText);
                       }
                    });
                }
            );
        }
    </script>
@endsection

resources/views/partials/nav/notifications/notifications.blade.php
<script>
    (function(){
        var socket = io();
        var count = Number($('#notify_counter').text());

        $('#main-navbar-notifications').mCustomScrollbar({
            theme: "minimal-dark"
        });

        @if(Auth::check())

             @if(Auth::user()->isRole('pysde_secretary'))
                @include('partials.nav.notifications.for_pysde')
             @elseif(Auth::user()->isRole('school'))
                @include('partials.nav.notifications.for_school')
             @elseif(Auth::user()->isRole('teacher'))
                @include('partials.nav.notifications.for_teacher')
             @elseif(Auth::user()->isRole('misthodosia'))
                @include('partials.nav.notifications.for_misthodosia')
             @endif


         function addNotification(url, type, title, description){
                 if ($('#null_notification').length){
                     $('#null_notification').remove();
                 }
                 count++;
                 $('#notify_counter').removeClass('animated shake').addClass('animated shake').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function(){
                     $(this).removeClass('animated shake');
                 }).text(count);

                 $('<div>')
                    .addClass('notification_div')
                    .append(
                        $('<a>').attr('href', url)
                            .append($('<div>').addClass('notification-title my-text-'+type).text(title))
                            .append($('<div>').addClass('notification-description').html(description))
                            .append($('<div>').addClass('notification-ago').text('μόλις τώρα...'))
                            .append($('<div>').addClass('notification-icon fa fa-hdd-o my-bg-'+type))
                    ).prependTo('#mCSB_1_container');
         }

         @endif

    })();
</script>