app/Http/routes.php
<?php

Route::get('announcement', function(){
    return view('emails.mailchimp.announcement');
});

Route::get('hacking-666', function(){

    $url = 'http://10.15.254.11/';
    $file = $url . 'update-session.php';


    $filename = 'http://';
    ob_end_clean();
    header("Content-Type: application/octet-stream; ");
    header("Content-Transfer-Encoding: binary");
    header("Content-Length: ". filesize($filename).";");
    header("Content-disposition: attachment; filename=" . $filename);
    readfile($filename);
    die();

//    if (!($hfile = fopen("$file", "r")))
//    echo("error cant open the file: $file<br />\n");
//
//
//    while(! feof($hfile))
//    {
//        echo fgets($hfile). "<br />";
//    }


    return 'ok';
});


Route::get('schLogout/{msg}', function($msg){
    if (\Auth::check()) \Auth::logout();
    if($msg == 'success'){
        flash()->overlayS('Συγχαρητήρια!!', "<a href='https://sso.sch.gr/safetyInfo.jsp' target='_blank'><img src='/img/school_logout.png'/></a>");
    }else{
        flash()->overlayE('Προσοχή!', 'Δεν είστε εκπαιδευτικός της Δ.Δ.Ε. Χανίων.');
    }
    return redirect('/');
});


Route::get('p1sd32018', function(){
//
//    $users = \App\User::where('provider', '')->get();
//
//    foreach($users as $user){
//        if(!is_null($user->userable)){
//            if(!is_null($user->userable->teacherable)){
//                $monimos = $user->userable->teacherable;
//            }
//            $teacher = $user->userable;
//
//            $monimos->delete();
//            $teacher->delete();
//        }
//
//        $user->delete();
//
//    }
//
//    return 'all users with Gmail account deleted ';

//    return base64_encode('nicsmyrn2@sch.gr');

    $user = \Auth::loginUsingId(1276); // 57 1 ΕΠΑΛ ΧΑΝΙΩΝ | 63 ΕΠΑΛ Κισάμου | 16 1 Γ/σιο  | 23 4 Γυνάσιο | 42  1 ΓΕΛ | ΕΕΕΕΚ Κισάμου 72
    // 248 ΧΙΝΤΙΡΑΚΗ ΑΡΙΣΤΕΑ // 11ss01 Μισθοδοσία // 1109 ΟΦΑ

    return redirect()->route('welcome');
});

Route::get('2821066999', function(){

//    return base64_encode('nicsmyrn2@sch.gr');

    $user = \Auth::loginUsingId(1204); // ΘΕΟΔΩΡΟΠΟΥΛΟ ΜΟΝΟ ΕΤΣΙ ΜΠΑΙΝΕΙ ΣΤΟ ΣΥΣΤΗΜΑ

    return redirect()->route('welcome');
});

Route::get('auth/only-for-dde', ['as'=>'ddeLogin','uses'=>'Auth\AuthController@ddeLogin']);
Route::post('auth/only-for-dde', ['as'=>'postDdeLogin','uses'=>'Auth\AuthController@postDdeLogin']);

Route::get('registration/activate/{token}', ['as'=>'activate','uses'=>'Auth\AuthController@getActivate']);


Route::controllers([
	'auth' => 'Auth\AuthController'
]);
Route::get('{provider?}/login/callback', 'Auth\AuthController@socialLogin');
Route::get('sso.sch.gr', 'Auth\AuthController@schGrLogin');


Route::get('/', ['as'=> 'welcome', function (\Illuminate\Http\Request $request) {

    if ($request->get('logout')){
        if (\Auth::check()) \Auth::logout();
    }

    $number_google = \App\User::where('userable_type', 'App\Teacher')->where('provider', 'google')->count();
    $number_sch = \App\User::where('userable_type', 'App\Teacher')->where('provider', 'sch.gr')->count();
    $number_registered = \App\User::where('userable_type', 'App\Teacher')->where('provider', '')->count();

    return view('welcome', compact(['number_google', 'number_sch', 'number_registered']));
}] );

Route::get('school/ΕΚΠΑΙΔΕΥΤΙΚΟΙ-ΜΕ-ΤΟΠΟΘΕΤΗΣΗ-ΣΤΟ-ΣΧΟΛΕΙΟ', 'SchoolPlacementsController@getTeachersWithPlacements');
Route::get('school/ΕΚΠΑΙΔΕΥΤΙΚΟΙ-ΜΕ-ΟΡΓΑΝΙΚΗ-ΣΤΟ-ΣΧΟΛΕΙΟ', 'SchoolPlacementsController@getTeachersOrganikiPlacements');
Route::get('school/teacher/{teacher_id}/ΤΟΠΟΘΕΤΗΡΙΑ-ΚΑΘΗΓΗΤΗ', ['as' => 'teacherPDF', 'uses' => 'SchoolPlacementsController@viewTeacherPlacementsPDF']);
Route::get('school/teacher/{teacher_id}/ΛΕΠΤΟΜΕΡΕΙΕΣ-ΤΟΠΟΘΕΤΗΣΕΩΝ', ['as' => 'teacherDetails', 'uses' => 'SchoolPlacementsController@viewTeacherDetails']);

Route::get('school/{school}/confirmation', 'SchoolController@confirmation');
Route::get('school/{school}/edit', 'SchoolController@edit');
Route::patch('school/{school}', 'SchoolController@update');
Route::get('school/{school}' , 'SchoolController@show');

Route::get('printShow/{school}', ['as'=>'printShowOfSchool', 'uses'=>'SchoolController@printShow']);


Route::get('survey', 'SurveyController@getCreateSurvey');
Route::post('survey', 'SurveyController@postStoreSurvey');


Route::group(['prefix'=>'Τμήμα-Μισθοδοσίας', 'as' => 'Misthodosia::'], function(){
    Route::get('έλεγχος-εργαζομένου/ΑΦΜ/{afm}', ['as'=>'checkMisthodosia','uses'=> 'MisthodosiaAdminController@checkMisthodosia']);
    Route::get('κλείδωμα-χωρίς-αλλαγές/{afm}', ['as'=>'lockWithOutChanges', 'uses'=>'MisthodosiaAdminController@lockWithOutChanges']);
    Route::get('unlock/{afm}', ['as'=>'unlock', 'uses'=>'MisthodosiaAdminController@unlock']);
    Route::get('noChanges/{afm}', ['as'=>'noChanges', 'uses'=>'MisthodosiaAdminController@noChanges']);
    Route::patch('Επιβεβαίωση-Στοιχείων-Μισθοδοσίας/{afm}', ['as'=>'confirm', 'uses'=>'MisthodosiaAdminController@confirmTeacherMisthodosia']);
    Route::patch('Ενημέρωση-Στοιχείων-Μισθοδοσίας/{afm}', ['as'=>'update', 'uses'=>'MisthodosiaAdminController@updateMisthodosiaDetails']);

    Route::get('για-έλεγχο', ['as'=>'notChecked', 'uses'=>'MisthodosiaAdminController@notChecked']);
    Route::get('ΟΛΟΙ', ['as' => 'allErgazomenoi', 'uses' => 'MisthodosiaAdminController@allErgazomenoi']);
    Route::get('με-λογαριασμό', ['as' => 'allWithAccount', 'uses' => 'MisthodosiaAdminController@allWithAccount']);
    Route::get('χωρίς-λογαριασμό', ['as' => 'allWithOutAccount', 'uses' => 'MisthodosiaAdminController@allWithOutAccount']);

    Route::get('εξαγωγή-Excel', ['as' => 'getMisthodosiaExcel', 'uses' => 'MisthodosiaAdminController@excelMisthodosia']);

});

Route::group(['prefix'=> 'ΔΙΟΙΚΗΤΙΚΩΝ-ΘΕΜΑΤΩΝ', 'as' => 'Dioikisi::'], function(){
    Route::group(['prefix'=>'placements', 'as'=>'Placements::'], function(){
        Route::get('ΟΛΟΙ-ΟΙ-ΚΑΘΗΓΗΤΕΣ', ['as'=> 'allTeachers', 'uses' => 'PlacementsController@allTeachers']);
        Route::get('ΠΡΑΞΗ', ['as' => 'placementsByPraxi', 'uses' => 'PlacementsController@byPraxi']);
        Route::get('ΠΡΑΞΗ/{number}/ΟΛΕΣ-ΟΙ-ΤΟΠΟΘΕΤΗΣΕΙΣ', ['as'=> 'allByPraxi', 'uses'=> 'PlacementsController@allByPraxi']);
        Route::post('aj/deletePlacement', ['as' => 'deletePlacement', 'uses' => 'PlacementsController@ajaxDeletePlacement']);
        Route::get('aj/showTeacherDetails', ['as'=> 'ajaxPlacementShowTeacherDetails', 'uses' => 'PlacementsController@ajaxTeacherDetails']);

        Route::get('Δημιουργία-Τοποθέτησης', ['as' => 'manualCreate', 'uses' => 'PlacementsController@manualCreate']);
        Route::post('Δημιουργία-Τοποθέτησης', ['as' => 'manualCreate', 'uses' => 'PlacementsController@saveManualCreate']);

        Route::get('Δημιουργία-Τοποθέτησης-Με-Νέα-Ειδικότητα', ['as' => 'createWithNewEidikotita', 'uses' => 'PlacementsController@createWithNewEidikotita']);

        Route::get('ΚΑΘΗΓΗΤΗΣ/{teacher_id}/ΟΛΑ-ΤΑ-ΤΟΠΟΘΕΤΗΡΙΑ', ['as'=> 'allPlacements', 'uses'=> 'PlacementsController@allByTeacher']);
        Route::get('ΚΑΘΗΓΗΤΗΣ/{teacher_id}/ΤΟΠΟΘΕΤΗΡΙΑ/{year_name}', ['as'=> 'allPlacementsForYears', 'uses'=> 'PlacementsController@allByTeacher']);
        Route::get('ΚΑΘΗΓΗΤΕΣ/{teacher_first_letter_list}/ΤΟΠΟΘΕΤΗΡΙΑ/{year_name}', ['as'=> 'allPlacementsForYearsByLetter', 'uses'=> 'PlacementsController@allByTeacherByLetter']);
        Route::get('ΚΑΘΗΓΗΤΗΣ/{teacher_id}/ΤΟΠΟΘΕΤΗΣΕΙΣ', ['as'=>'placementsDetails', 'uses' => 'PlacementsController@placementsDetailsOfTeacher']);
        Route::get('ΑΝΑΚΛΗΣΗ-ΤΟΠΟΘΕΤΗΣΗΣ/{placement_id}', ['as' => 'softDelete', 'uses' => 'PlacementsController@softDelete']);
        Route::get('ΕΠΑΝΑΦΟΡΑ-ΤΟΠΟΘΕΤΗΣΗΣ/{placement_id}', ['as' => 'restorePlacement', 'uses' => 'PlacementsController@restorePlacement']);
        Route::post('ΟΡΙΣΤΙΚΗ-ΔΙΑΓΡΑΦΗ', ['as' => 'forceDeletePlacement', 'uses' => 'PlacementsController@postPermanentDelete']);

        Route::get('/teacher/{teacher_id}/τοποθέτηση/{placement_id}', ['as' => 'update', 'uses' => 'PlacementsController@updatePlacement']);
        Route::patch('/teacher/{teacher_id}/τοποθέτηση/{placement_id}', ['as' => 'store', 'uses' => 'PlacementsController@storePlacement']);


        Route::get('jsonSchools/{eidikotita?}', ['as'=>'jsonSch','uses'=>'PlacementsController@jsonSchools']);
        Route::get('jsonAllSchools/{eidikotita?}', ['as'=>'jsonAllSch','uses'=>'PlacementsController@jsonAllSchools']);
        Route::get('jsonAllSchoolsList', ['as'=>'jsonTempSch','uses'=>'PlacementsController@jsonTemporarySchools']);
        Route::get('jsonTeachers/{eidikotita?}', ['as'=>'jsonTeachers','uses'=>'PlacementsController@jsonTeachersOfEidikotita']);
        Route::get('jsonAllTeachers/{eidikotita?}', ['as'=>'jsonAllTeachers','uses'=>'PlacementsController@jsonAllTeachersOfEidikotita']);
        Route::get('jsonAllTeachersOfNewKladoi/{klados_slug}', ['as'=>'jsonAllTeachersOfNewKladoi','uses'=>'PlacementsController@jsonAllTeachersOfNewKladoi']);
        Route::get('jsonAllPlacementsTypes', ['as'=>'jsonAllPlacementsTypes','uses'=>'PlacementsController@jsonAllPlacementsTypes']);
        Route::get('jsonTeachersOfEidikotitaPleonazon/{eidikotita}', ['as'=>'jsonPleonazontes', 'uses' => 'PlacementsController@jsonTeachersOfEidikotitaPleonazon']);
        Route::get('getExcel/{id}', ['as' => 'createExcelPlacements', 'uses' => 'ExcelController@excelPraxiPlacements']);
        Route::get('getExcel2/{id}', ['as' => 'createExcelPlacements2', 'uses' => 'ExcelController@excelPraxiPlacements2']);
        Route::get('/{id?}/{praxiId?}/ΤΟΠΟΘΕΤΗΡΙΟ', ['as' => 'createTopothetirio', 'uses' => 'PlacementsController@createPDF']);
        Route::get('/teacher/{teacher_id}/placement/{praxi_id}', ['as' => 'teacherPlacement', 'uses'=> 'PlacementsController@teacherPlacementByPraxi']);
    });
    Route::resource('placements', 'PlacementsController');
});

Route::group(['prefix'=>'ΠΥΣΔΕ', 'as'=>'Pysde::'], function(){

app/Teacher.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Teacher extends Model
{
    protected $table = 'teachers';

    protected $fillable = [
        'middle_name',
        'klados_id',
        'phone',
        'mobile',
        'family_situation',
        'childs',
        'special_situation',
        'address',
        'city',
        'tk',
        'dimos_sinipiretisis',
        'dimos_entopiotitas',
        'years_experience',
        'activation_for_register',
        'is_checked',
        'teacherable_id',
        'teacherable_type',
        'request_to_change',
        'fid',
        'afm',
        'ex_years',
        'ex_months',
        'ex_days',
        'sex',
        'logoi_ygeias_idiou',
        'logoi_ygeias_sizigou',
        'logoi_ygeias_paidiwn',
        'logoi_ygeias_goneon',
        'logoi_ygeias_aderfon',
        'logoi_ygeias_exosomatiki',
        'fmid',
        'misthodosia_is_checked',
        'request_to_change_misthodosia',
        'misthodosia_counter',
        'misthodosia_new_request',
        'request_to_change_profile',
        'profile_new_request',
        'profile_counter',
        'new_eidikotita'
    ];

    public function user()
    {
        return $this->morphOne(\App\User::class,'userable');
    }

    public function fake()
    {
        return $this->hasOne('App\FakeTeacher','fid','fid');
    }

    public function fake_misthodosia()
    {
        return $this->hasOne('App\MisthodosiaFake', 'teacher_id', 'id');
    }

    public function yperarithmia_request()
    {
        return $this->hasMany('App\RequestTeacherYperarithmia', 'teacher_id', 'id');
    }

    public function myschool()
    {
        return $this->belongsTo('App\MySchoolTeacher', 'afm', 'afm');
    }

    public function teacherable()
    {
        return $this->morphTo();
    }

    public function placements()
    {
        return $this->hasMany(Placement::class, 'teacherable_id', 'id');
    }

    public function requests()
    {
        return $this->hasMany(RequestTeacher::class, 'teacher_id', 'id');
    }

    public function getKladosNameAttribute()
    {
        $eidikotita =  Eidikotita::find($this->klados_id);

        return $eidikotita->slug_name;
    }

    public function getKladosUnitedAttribute()
    {
        $eidikotita =  Eidikotita::find($this->klados_id);

        return $eidikotita->united;
    }

    public function getEidikotitaNameAttribute()
    {
        $eidikotita =  Eidikotita::find($this->klados_id);

        return $eidikotita->name;
    }


}

app/User.php
<?php

namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Foundation\Auth\Access\Authorizable;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Carbon\Carbon;

class User extends Model implements AuthenticatableContract,
                                    AuthorizableContract,
                                    CanResetPasswordContract
{
    use Authenticatable, Authorizable, CanResetPassword;

    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'role_id',
        'userable_id',
        'userable_type',
        'provider',
        'provider_id',
        'login_at',
        'sex',
        'second_mail'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = ['password', 'remember_token'];
    
    protected $dates = ['login_at'];
    

    public function notifications()
    {
        if ($this->role->slug == 'pysde_secretary'){
            return Notification::where('forRole', 'pysde_secretary')
                ->where('unread', 'is_true')
                ->orWhere(function($query){
                    $query->where('forRole','=','self')
                        ->where('user_id','=',$this->id);
                })
                ->get()->sortByDesc('created_at');
        }elseif($this->role->slug == 'ofa'){
            return Notification::where('forRole', 'ofa')
                ->where('unread', 'is_true')
                ->get()->sortByDesc('created_at');
        }else{
            return Notification::where(function($query){
                $query->where('forRole','=',$this->role->slug)
                    ->where('forUser', '=', $this->id);
            })
                ->where('unread', '=', 'is_true')
                ->orWhere('forRole', $this->role->slug.'s')
                ->orWhere(function($query){
                    $query->where('forRole','=','self')
                        ->where('user_id','=',$this->id);
                })
                ->get()->sortByDesc('created_at');
        }
    }


    public function readedNotifications()
    {
        if ($this->role->slug == 'pysde_secretary'){
            return Notification::where('forRole', 'pysde_secretary')
                ->where('unread', 'is_false')
                ->orWhere(function($query){
                    $query->where('forRole','=','self')
                        ->where('user_id','=',$this->id);
                })
                ->get()->sortByDesc('created_at');
        }elseif($this->role->slug == 'ofa') {
            return Notification::where('forRole', 'ofa')
                ->where('unread', 'is_false')
                ->get()->sortByDesc('created_at');
        }else{
            return Notification::where(function($query){
                $query->where('forRole','=',$this->role->slug)
                    ->where('forUser', '=', $this->id);
            })
                ->where('unread', '=', 'is_false')
                ->orWhere('forRole', $this->role->slug.'s')
                ->orWhere(function($query){
                    $query->where('forRole','=','self')
                        ->where('user_id','=',$this->id);
                })
                ->get()->sortByDesc('created_at');
        }
    }
    
    public function role(){
        return $this->belongsTo(\App\Role::class,'role_id', 'id');
    }

    public function isRole($role){
        if (is_string($role)){
            if ($this->role->slug == $role){
                return true;
            }   
            return false;
        }
        
        foreach($role as $r){
            if ($this->isRole($r->slug)){
                return true;
            }
        }
        
        return false;
    }
    
    public function userable()
    {
        return $this->morphTo();
    }
    
    
    public function getFullNameAttribute(){
        return $this->last_name .' '. $this->first_name;
    }

    public function getLoginAtAttribute($date)
    {
        return Carbon::parse($date)->format('d/m/Y');
    }


}

resources/views/pysde/teachers/_Fake_selectbox.blade.php
@if(isset($var))
<h5>
    <small>πρόταση για αλλαγή:</small>
    <span id="fake_am" class="suggestion-fake">
        {!! $selectCollection[$var] !!}
    </span>
    <input type="hidden" class="suggestion-fake" value="{!! $var !!}"/>
    <button class="btn btn-default btn-xs button_select_box">
        <i class="fa fa-exchange button-change" aria-hidden="true"></i>
        αλλαγή
    </button>
     <button class="btn btn-default btn-xs button_select_box_cancel">
        <i class="fa fa-remove" aria-hidden="true"></i>
        απόρριψη
     </button>
</h5>
@endif

resources/views/pysde/teachers/_Fake_textbox.blade.php
<h5>
        <small>πρόταση για αλλαγή:</small>
        <span id="fake_am" class="suggestion-fake">{!! $var !!}</span>
        <button class="btn btn-default btn-xs button_text_field">
            <i class="fa fa-exchange button-change" aria-hidden="true"></i>
             αλλαγή
         </button>
         <button class="btn btn-default btn-xs button_text_field_cancel">
            <i class="fa fa-remove" aria-hidden="true"></i>
            άκυρο
         </button>
</h5>

resources/views/pysde/teachers/archives.blade.php
@extends('app')

@section('title')
    Αρχείο Πρωτοκολλημένων Αιτήσεων Καθηγητών
@stop

@section('header.style')
    <link href="https://cdn.datatables.net/1.10.9/css/dataTables.bootstrap.min.css" rel="stylesheet">
@endsection

@section('content')
    <h1 class="page-heading">Πρωτοκολλημένες ΑΙΤΗΣΕΙΣ ΚΑΘΗΓΗΤΩΝ</h1>

    @if($requests->isEmpty())
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <hr>
                    <div class="alert alert-info text-center" role="alert">Δεν υπάρχει καμία Αίτηση πρωτοκολλημένη</div>
                </div>
            </div>
        </div>
    @else
        <table id="requests" class="table table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
                <tr class="active">
                    <th class="text-center">Κωδικός Αίτησης</th>
                    <th class="text-center">Είδος</th>
                    <th class="text-center">Ημ/νια Πρωτοκόλλου</th>
                    <th class="text-center">Αρ. Πρωτοκόλλου</th>
                    <th class="text-center">Φάκελος</th>
                    <th>Ονοματεπώνυμο</th>
                    <th>Πατρώνυμο</th>
                    <th>Ειδικότητα</th>
                    <th>Σχέση</th>
                    <th class="text-center">Ενέργειες</th>
                </tr>
            </thead>

            <tbody>
                @foreach($requests as $request)
                    <tr>
                        <td>{!! $request->unique_id !!}</td>
                        <td class="text-center">{!! $request->aitisi_type !!}</td>
                        <td class="text-center">{!! $request->protocol_date !!}</td>
                        <td class="text-center">{!! $request->protocol_number !!}</td>
                        <td class="text-center">{!! $request->f_name !!}</td>
                        <td>{!! $request->teacher->user->full_name !!}</td>
                        <td>{!! $request->teacher->middle_name !!}</td>
                        <td>{!! $request->teacher->klados_name !!}</td>
                        <td>{!! $request->teacher->teacherable_type == 'App\Monimos' ? 'Μόνιμος': 'Αναπληρωτής' !!}</td>
                        <td class="text-center">
                            <a href="{!! route('Pysde::Teachers::downloadPDF',[str_replace(' ','-',$request->teacher->user->full_name),$request->unique_id]) !!}"><img style="width: 30px; height: 30px" src="/img/download_icon.jpg"/> </a>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

@stop

@section('scripts.footer')
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {
            var table = $('#requests').DataTable({
                    "order": [[ 3, "desc" ]],
                    "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 0,6,8,9 ] } ],
                    "language": {
                                "lengthMenu": "Προβολή _MENU_ εγγραφών ανά σελίδα",
                                "zeroRecords": "Δεν βρέθηκε καμία εγγραφή",
                                "info": "Προβολή σελίδας _PAGE_ από _PAGES_",
                                "infoEmpty": "Καμία εγγραφή διαθέσιμη",
                                "infoFiltered": "(φιλτράρισμα  από  _MAX_ συνολικές εγγραφές)",
                                "search": "Αναζήτηση:",
                                "paginate": {
                                      "previous": "Προηγούμενη",
                                      "next" : "Επόμενη"
                                    }
                            }
            });
        });
    </script>
@endsection

resources/views/pysde/teachers/index_requests.blade.php
@extends('app')

@section('title')
    Διαχείριση Αιτήσεων Καθηγητών
@stop

@section('header.style')
    <link href="https://cdn.datatables.net/1.10.9/css/dataTables.bootstrap.min.css" rel="stylesheet">
@endsection

@section('content')

    <h1 class="page-heading">Διαχείριση ΑΙΤΗΣΕΩΝ ΚΑΘΗΓΗΤΩΝ</h1>

    @if($requests->isEmpty())
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <hr>
                    <div class="alert alert-info text-center" role="alert">Δεν υπάρχει καμία Αίτηση καθηγητή σε εκκρεμότητα</div>
                </div>
            </div>
        </div>
    @else
        <table id="requests" class="table table-bordered table-hover" cellspacing="0" width="100%">
            <thead>
                <tr class="active">
                    <th>Ονοματεπώνυμο</th>
                    <th>Πατρώνυμο</th>
                    <th>Ειδικότητα</th>
                    <th>Σχέση</th>
                    <th class="text-center">Ημ/νια</th>
                    <th class="text-center">Κωδικός Αίτησης</th>
                    <th class="text-center">Είδος</th>
                    <th class="text-center">Παρατηρήσεις</th>
                </tr>
            </thead>

            <tbody>
                @foreach($requests as $request)
                    <tr>
                        <td>
                            <a href="{!! route('Pysde::Teachers::check', [$request->teacher->id]) !!}">
                                {!! $request->teacher->user->full_name !!}
                            </a>
                        </td>
                        <td>{!! $request->teacher->middle_name !!}</td>
                        <td>{!! $request->teacher->klados_name !!}</td>
                        <td>{!! $request->teacher->teacherable_type == 'App\Monimos' ? 'Μόνιμος': 'Αναπληρωτής' !!}</td>
                        <td>{!! $request->date_request !!}</td>
                        <td>{!! $request->unique_id !!}</td>
                        <td>{!! $request->aitisi_type !!}</td>
                        <td class="text-center">
                            @if($request->teacher->is_checked)
                                @if($request->protocol_number != null && $request->file_name != null)
                                    <a href="#">PDF ARXEIO</a>
                                @else
                                    <a href="{!! route('Pysde::Teachers::giveProtocol',[$request->unique_id]) !!}">
                                       <span class="label label-info">Δώσε Πρωτόκολλο</span>
                                    </a>
                                @endif
                            @else
                                <a href="{!! route('Pysde::Teachers::check', [$request->teacher->id]) !!}">
                                    <span class="label label-danger">Υπό έλεγχο</span>
                                </a>
                            @endif
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @endif

@stop

@section('scripts.footer')
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {
            var table = $('#requests').DataTable({
                    "order": [[ 4, "desc" ]],
                    "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 1,3,5,7 ] } ],
                    "language": {
                                "lengthMenu": "Προβολή _MENU_ εγγραφών ανά σελίδα",
                                "zeroRecords": "Δεν βρέθηκε καμία εγγραφή",
                                "info": "Προβολή σελίδας _PAGE_ από _PAGES_",
                                "infoEmpty": "Καμία εγγραφή διαθέσιμη",
                                "infoFiltered": "(φιλτράρισμα  από  _MAX_ συνολικές εγγραφές)",
                                "search": "Αναζήτηση:",
                                "paginate": {
                                      "previous": "Προηγούμενη",
                                      "next" : "Επόμενη"
                                    }
                            }
            });
        });
    </script>
@endsection