app/Http/routes.php
        Route::post('επιλογή-δρομολογίων', ['as' => 'postChosenRoutes', 'uses' => 'KTEL\SchoolKtelController@postChosenRoutes']);
        Route::get('διαχείριση-δρομολογίων',['as' => 'editPeriods', 'uses' => 'KTEL\SchoolKtelController@editRoutePeriods']);
        Route::get('ΒΕΒΑΙΩΣΗ-ΜΕΤΑΦΕΡΟΜΕΝΩΝ-ΜΑΘΗΤΩΝ/{year}/{month}', ['as'=> 'viewPDF', 'uses'=> 'KTEL\SchoolKtelController@showPDFperiodRoute']);
        Route::get('Λίστα-Βεβαιώσεων', ['as' => 'listPdf', 'uses' => 'KTEL\SchoolKtelController@listPdf']);
        Route::get('download/{file}', ['as'=>'downloadPDF', 'uses'=>'KTEL\SchoolKtelController@downloadPDF']);
    });
});


Route::group(['prefix'=>'ajax', 'as'=>'ajax::'], function(){
    /*
     * AJAX REQUESTS FOR SCHOOLS
     */
    Route::get('/ktel/getAbsences/{periodRoute}', ['as'=>'getAbsences', 'uses' => 'KTEL\AjaxKtelSchoolController@getSpecificAbsences']);
    Route::post('/ktel/updateAbsences', ['as'=>'updateAbsences', 'uses' => 'KTEL\AjaxKtelSchoolController@updateAbsences']);
    Route::post('/ktel/insertAbsences', ['as'=>'insertAbsences', 'uses' => 'KTEL\AjaxKtelSchoolController@insertAbsences']);
    Route::get('/ktel/existingroutes', ['as' => 'getBusRoute', 'uses' => 'KTEL\AjaxKtelSchoolController@getExistingRoutes']);
    Route::get('/ktel/existingroutesEnabled', ['as' => 'getBusRouteEnabled', 'uses' => 'KTEL\AjaxKtelSchoolController@getExistingRoutes_ENABLED']);
    Route::get('/ktel/getPeriodRoutes/{periodId}', ['as' => 'getPeriodRoutes', 'uses' => 'KTEL\AjaxKtelSchoolController@getPeriodRoutes']);
    Route::get('/ktel/getYears', ['as'=>'getYears', 'uses' => 'KTEL\AjaxKtelSchoolController@getAllYears']);
    Route::get('/ktel/school/municipalities', ['as' => 'allSchoolMunicipalities', 'uses' => 'KTEL\AjaxKtelSchoolController@allMunicipalities']);
    Route::get('/ktel/school/busroutes/{m_id}', ['as' => 'getSchoolBusRoute', 'uses' => 'KTEL\AjaxKtelSchoolController@getBusRoute']);
    Route::post('/ktel/insertPeriodRoutes', ['as' => 'insertPeriods', 'uses' => 'KTEL\AjaxKtelSchoolController@insertPeriodRoutes']);
    Route::post('/ktel/updatePeriodRoutes', ['as' => 'updatePeriodRoutes', 'uses' => 'KTEL\AjaxKtelSchoolController@updatePeriodRoutes']);

    /*
     *  AJAX REQUESTS FOR KTEL ADMIN
     */
    Route::post('/ktel/changePermission', ['as'=>'changePermission', 'uses' => 'KTEL\AjaxKtelDdeController@changePermission']);

    Route::get('/ktel/getPeriodCollection', ['as'=>'getPeriodCollection', 'uses' => 'KTEL\AjaxKtelDdeController@getPeriodCollection']);
    Route::delete('ktel/busroutes/{route}', ['as' => 'deleteRoute', 'uses' => 'KTEL\AjaxKtelDdeController@deleteRoute']);
    Route::get('/ktel/routetypes', ['as' => 'getRouteTypes', 'uses' => 'KTEL\AjaxKtelDdeController@getRouteTypes']);
    Route::get('/ktel/municipalities', ['as' => 'allMunicipalities', 'uses' => 'KTEL\AjaxKtelDdeController@allMunicipalities']);
    Route::get('/ktel/busroutes/{m_id}', ['as' => 'getBusRoute', 'uses' => 'KTEL\AjaxKtelDdeController@getBusRoute']);  //22222222222
    Route::post('/ktel/busroutes', ['as' => 'updateBusRoute', 'uses' => 'KTEL\AjaxKtelDdeController@updateBusRoute']);
    Route::post('/ktel/addroute', ['as' => 'addRoute', 'uses' => 'KTEL\AjaxKtelDdeController@addRoute']);
});
/*
 * **********************   K T E L  E N D  ******************
 */


/*
 * **********************   O F A   S T A R T S  ******************
 */
Route::group(['prefix'=>'ΑΘΛΗΤΙΚΟΙ-ΑΓΩΝΕΣ', 'as'=>'OFA::'], function() {
    Route::get('Λίστα-Ομαδικών-Αθλημάτων', ['as' => 'sportList', 'uses' => 'OFA\SchoolOfaController@getLists']);
    Route::get('Κατάσταση-Συμμετοχής-Ατομικών-Αθλημάτων', ['as' => 'sportListIndividual', 'uses' => 'OFA\SchoolOfaController@getListsIndividual']);
    Route::get('Αθλοπαιδεία', ['as' => 'sportEducation', 'uses' => 'OFA\SchoolOfaPrimaryController@getSportEducation']);
    Route::get('Κατάσταση-Συμμετοχής', ['as' => 'sportParticipationStatus', 'uses' => 'OFA\SchoolOfaParticipationsController@getParticipationStatus']);

    Route::get('ΑΡΧΕΙΟ-ΔΗΛΩΣΕΩΝ', ['as' => 'archivesStatements', 'uses' => 'OFA\SchoolOfaPrimaryController@archivesStatements']);
    Route::get('ΑΡΧΕΙΟ-ΔΗΛΩΣΕΩΝ-ΛΥΚΕΙΩΝ', ['as' => 'archivesStatementsHighSchool', 'uses' => 'OFA\SchoolOfaController@archivesStatementsHighSchool']);

    Route::get('Καταστάσεις-Μαθητών', ['as' => 'listOfStudents', 'uses' => 'OFA\SchoolOfaController@listOfStudents']);
    Route::get('Καταστάσεις-Μαθητών-Γυμνασίου', ['as' => 'listOfStudentsPrimary', 'uses' => 'OFA\SchoolOfaPrimaryController@listOfStudentsPrimary']);

    Route::get('ΜΑΘΗΤΗΣ/{student}', ['as' => 'editStudent', 'uses' => 'OFA\SchoolOfaController@editStudent']);
    Route::post('ΜΑΘΗΤΗΣ/{student}', ['as' => 'updateStudent', 'uses' => 'OFA\SchoolOfaController@updateStudent']);
    Route::post('delete/specificStudent', ['as' => 'deleteStudent', 'uses' => 'OFA\SchoolOfaController@deleteStudentFromSpecificSchool']);
    Route::post('insertFromMyschool', ['as' => 'insertStudentsFromMySchool', 'uses' => 'OFA\SchoolOfaController@insertStudentsFromMySchool']);


    Route::get('ΜΑΘΗΤΗΣ/primary/{student}', ['as' => 'primary.editStudent', 'uses' => 'OFA\SchoolOfaPrimaryController@editStudent']);
    Route::post('ΜΑΘΗΤΗΣ/primary/{student}', ['as' => 'primary.updateStudent', 'uses' => 'OFA\SchoolOfaPrimaryController@updateStudent']);
    Route::post('delete/primary/specificStudent', ['as' => 'primary.deleteStudent', 'uses' => 'OFA\SchoolOfaPrimaryController@deleteStudentFromSpecificSchool']);
    Route::post('primary/insertFromMyschool', ['as' => 'primary.insertStudentsFromMySchool', 'uses' => 'OFA\SchoolOfaPrimaryController@insertStudentsFromMySchool']);

    Route::group(['prefix'=>'ΔΙΑΧΕΙΡΙΣΗ', 'as'=>'admin::'], function() {
        Route::get('Statistics', ['as' => 'statistics', 'uses' => 'OFA\AdminOfaController@statistics']);
        Route::get('Λίστες-Συμμετοχής', ['as' => 'adminShowLists', 'uses' => 'OFA\AdminOfaController@getLists']);
        Route::get('Λίστες-Συμμετοχής-Συνολικά', ['as' => 'adminShowGlobalLists', 'uses' => 'OFA\AdminOfaController@getGlobalLists']);
        Route::get('Λίστα-Αγώνων/{token}', ['as' => 'showListAdmin', 'uses' => 'OFA\AdminOfaController@showList']);
        Route::get('Κατάσταση-Συμμετοχής/{token}', ['as' => 'showParticipationAdmin', 'uses' => 'OFA\AdminOfaController@showParticipation']);
        Route::get('downloadList/{year_name}/{sport_name}/{gender}/{school_name}/{school_type}', ['as' => 'downloadPdfListAdmin', 'uses' => 'OFA\AdminOfaController@downloadOfaPdfList']);
        Route::post('aj/ofa/ParticipationStatus/pdfStream/{school_id}', ['as' => 'pdfParticipationStatusAdmin', 'uses' => 'OFA\AdminOfaController@pdfParticipationStatus']);


        Route::get('toggleLock/{list_id}', ['as' => 'toggleLock', 'uses' => 'OFA\AdminOfaController@toggleLock']);

        Route::get('for/{forSchool}', ['as' => 'showLists', 'uses' => 'OFA\AdminOfaController@showLists']);
    });

    Route::get('Λίστα-Αγώνων/{token}', ['as' => 'showList', 'uses' => 'OFA\SchoolOfaController@showList']);
    Route::get('Αρχείο-Αθλοπαιδεία/{token}', ['as' => 'showListPrimary', 'uses' => 'OFA\SchoolOfaPrimaryController@showListPrimary']);
    Route::get('Κατάσταση-Συμμετοχής/{token}', ['as' => 'showParticipation', 'uses' => 'OFA\SchoolOfaController@showParticipation']);

});

Route::get('aj/ofa/fetchDataForLists', ['as' => 'fetchNotifications', 'uses' => 'OFA\SchoolOfaController@fetchDataForLists']);
Route::get('aj/ofa/fetchDataForListsIndividual', ['as' => 'fetchNotifications', 'uses' => 'OFA\SchoolOfaController@fetchDataForListsIndividual']);

Route::post('aj/ofa/insertNewStudent', ['as' => 'insertNewStudent', 'uses' => 'OFA\SchoolOfaController@insertNewStudent']);
Route::post('aj/ofa/insertNewStudentPrimary', ['as' => 'insertNewStudentPrimary', 'uses' => 'OFA\SchoolOfaPrimaryController@insertNewStudent']);

Route::post('aj/ofa/insertNewList', ['as' => 'insertNewList', 'uses' => 'OFA\SchoolOfaController@insertNewList']);

Route::post('aj/ofa/insertNewListIndividual', ['as' => 'insertNewListIndividual', 'uses' => 'OFA\SchoolOfaController@insertNewListIndividual']);
Route::post('aj/ofa/insertNewListIndividualPrimary', ['as' => 'insertNewListIndividualPrimary', 'uses' => 'OFA\SchoolOfaPrimaryController@insertNewListIndividual']);

Route::post('aj/ofa/temporarySaveNewList', ['as' => 'temporarySaveNewList', 'uses' => 'OFA\SchoolOfaController@temporarySaveNewList']);

Route::post('aj/ofa/temporarySaveNewListIndividual', ['as' => 'temporarySaveNewListIndividual', 'uses' => 'OFA\SchoolOfaController@temporarySaveNewListIndividual']);
Route::post('aj/ofa/temporarySaveNewListIndividualPrimary', ['as' => 'temporarySaveNewListIndividualPrimary', 'uses' => 'OFA\SchoolOfaPrimaryController@temporarySaveNewListIndividual']);

Route::post('aj/ofa/checkIfListAlreadyExists', ['as' => 'checkIfListAlreadyExists', 'uses' => 'OFA\SchoolOfaController@checkIfListAlreadyExists']);
Route::post('aj/ofa/checkIfListAlreadyExistsForIndividual', ['as' => 'checkIfListAlreadyExists', 'uses' => 'OFA\SchoolOfaController@checkIfListAlreadyExistsForIndividual']);
Route::post('aj/ofa/checkIfListAlreadyExistsForIndividualPrimary', ['as' => 'checkIfParticipationPrimaryAlreadyExists', 'uses' => 'OFA\SchoolOfaPrimaryController@checkIfParticipationPrimaryAlreadyExists']);
Route::get('downloadList/{year_name}/{sport_name}/{gender}', ['as' => 'downloadPdfList', 'uses' => 'OFA\SchoolOfaController@downloadOfaPdfList']);

Route::get('aj/ofa/fetchDataForParticipationStatus', ['as' => 'fetchDataForParticipationStatus', 'uses' => 'OFA\SchoolOfaParticipationsController@fetchDataForParticipationStatus']);
Route::post('aj/ofa/fetchStudentsFromParticipationStatus', ['as' => 'fetchStudentsFromParticipationStatus', 'uses' => 'OFA\SchoolOfaParticipationsController@fetchStudentsFromParticipationStatus']);

app/Models/DIPE/OFA/SpecialSport.php
<?php

namespace App\Models\OFA;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SpecialSport extends Model
{
    use SoftDeletes;

    protected $connection = 'dipe';

    protected $table = 'ofa_special_sports';

    protected $fillable = [
        'name',
        'sport_id'
    ];

    protected $dates = ['deleted_at'];

    public function sport()
    {
        return $this->belongsTo(Sport::class, 'sport_id', 'id');
    }
}

app/Models/DIPE/OFA/SportList.php
<?php

namespace App\Models\OFA;


use App\School;
use App\Year;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class SportList extends Model
{
    protected $connection = 'dipe';

    protected $table = 'ofa_lists';

    protected $fillable = [
        'year_id',
        'school_id',
        'sport_id',
        'gender',
        'teacher_name',
        'synodos',
        'filename',
        'locked'
    ];


    public function year()
    {
        return $this->belongsTo(Year::class, 'year_id', 'id');
    }

    public function school()
    {
        return $this->belongsTo(School::class, 'school_id', 'id');
    }

    public function sport()
    {
        return $this->belongsTo(Sport::class, 'sport_id', 'id');
    }

    public function details()
    {
        return $this->hasMany(SportListDetails::class, 'list_id', 'id');
    }

    public function participations()
    {
        return $this->hasMany(SportParticipation::class, 'list_id', 'id');
    }


    public function getUpdatedAtAttribute($date)
    {
        return Carbon::parse($date)->format('d/m/Y H:i:s');
    }
}

app/Http/Controllers/OFA/AdminOfaController.php
<?php

namespace App\Http\Controllers\OFA;

use App\Http\Controllers\Controller;


use App\Http\Requests\StudentRequest;
use App\Models\OFA\SportList;
use App\Models\OFA\SportListDetails;
use App\Models\OFA\SportParticipation;
use App\Models\OFA\SportParticipationDetails;
use App\Models\OFA\Student;
use App\Notification;
use App\School;
use Illuminate\Http\Request;

use App\Models\OFA\Sport;
use App\Year;
use App\Http\Controllers\OFA\traits\OutputOfaTrait;

class AdminOfaController extends Controller
{

    use OutputOfaTrait;

    public function __construct()
    {
//        $this->middleware('ofaAdmin');

//        \Auth::loginUsingId(1109); //16 1ο Γυμνάσιο, 57 1 ΕΠΑΛ ΧΑΝΙΩΝ  | 23 4 Γυνάσιο | 42  1 ΓΕΛ
    }

    public function statistics(Request $request)
    {
        $gym = School::where('type', 'gym')->lists('id');
        $lykeia = School::where('type', 'lyk')->orWhere('type', 'epal')->lists('id');
        $dimotika = School::where('type', 'dimotika')->lists('id');



        if($request->get('first') == 'high-school'){
            $first_statistic_array = SportList::with('details')->whereIn('school_id', $lykeia)->where('locked', true)->get()->groupBy('sport_id');
        }elseif($request->get('first') == 'secondary-school'){
            $first_statistic_array = SportList::with('details')->whereIn('school_id', $gym)->where('locked', true)->get()->groupBy('sport_id');
        }elseif($request->get('first') == 'primary-school'){
            $first_statistic_array = SportList::with('details')->whereIn('school_id', $dimotika)->where('locked', true)->get()->groupBy('sport_id');
        }else{
            $first_statistic_array = SportList::with('details')->whereIn('school_id', $lykeia)->where('locked', true)->get()->groupBy('sport_id');
        }

        if($request->get('second') == 'high-school'){
            $second_statistic_array = SportList::with('details')->whereIn('school_id', $lykeia)->where('locked', true)->get()->groupBy('sport_id');
        }elseif($request->get('second') == 'secondary-school'){
            $second_statistic_array = SportList::with('details')->whereIn('school_id', $gym)->where('locked', true)->get()->groupBy('sport_id');
        }elseif($request->get('second') == 'primary-school'){
            $second_statistic_array = SportList::with('details')->whereIn('school_id', $dimotika)->where('locked', true)->get()->groupBy('sport_id');
        }else{
            $second_statistic_array = SportList::with('details')->whereIn('school_id', $lykeia)->where('locked', true)->get()->groupBy('sport_id');
        }


        $teams = collect();
        $students = collect();


        foreach($first_statistic_array as $key=>$sportLists){
            $teams->push([
                'sport_name'    => Sport::find($key)->name,
                'female'        => $sportLists->where('gender', 0)->count(),
                'male'          => $sportLists->where('gender', 1)->count(),
                'sum'           => $sportLists->count()
            ]);

        }


        foreach($second_statistic_array as $key=>$sportLists){
            $sumMale = 0;
            $sumFemale = 0;

            foreach($sportLists as $sportList){
                if($sportList->gender == 0){
                    $sumFemale += $sportList->details->count();
                }else{
                    $sumMale += $sportList->details->count();
                }
            }

            $students->push([
                'sport_name'    => Sport::find($key)->name,
                'female_counter'        => $sumFemale,
                'male_counter'          => $sumMale,
                'sum'           => ($sumFemale + $sumMale)
            ]);
        }

        $school_types = [
            'high-school' => 'ΛΥΚΕΙΑ - ΕΠΑΛ',
            'secondary-school' => 'ΓΥΜΝΑΣΙΑ',
            'primary-school'    => 'ΔΗΜΟΤΙΚΑ'
        ];


        return view('OFA.admin.statistics', compact('teams', 'students', 'school_types'));
    }

    public function getLists()
    {
        $schools = School::where('type', 'lyk')->orWhere('type', 'epal')->get();

        return view('OFA.admin.show-all-lists', compact('schools'));
    }

    public function getGlobalLists()
    {
        $lists = SportList::with(['year', 'school'])->whereNotNull('filename')->get();

        return view('OFA.admin.all-lists-by-filter', compact('lists'));
    }

    public function toggleLock($list_id)
    {
        $list = SportList::find($list_id);

        $list->locked = $list->locked ? false : true;

        $list->save();

        flash()->success('Εντάξει...');

        return redirect()->back();
    }

    public function showLists(School $school, Request $request)
    {

        $action = $request->get('action');
        if($action != null){
            Notification::where('uniqueAction', $action)->update([
                'unread' => 'is_false'
            ]);
        }

        $name = $school->name;

        $schools = School::where('type', 'lyk')->orWhere('type', 'epal')->orWhere('type', 'gym')->get();

        $lists = SportList::where('school_id', $school->id)->get();

        $parts = collect();


        foreach($lists as $list){
            foreach($list->participations as $participation){
                $parts->push([
                    'year_name' => $list->year->name,
                    'year_id'   => $list->year_id,
                    'individual'   => $list->sport->individual,
                    'sport_name'    => $list->sport->name,
                    'gender'        => $list->gender,
                    'synodos'       => $list->synodos,
                    'phase'         => $participation->phase,
                    'part_id'       => $participation->id,
                    'checkedStudents'  => $participation->details->pluck('student_id')->all()
                ]);
            }
        }

        $school_id = $school->id;

        return view('OFA.admin.show-school-list', compact('schools', 'name', 'lists', 'parts', 'school_id'));

    }
}

resources/views/OFA/admin/_index-lists-by-filter.blade.php
        @if($lists->isEmpty())
            <div class="container">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        <hr>
                        <div class="alert alert-info text-center" role="alert">Δεν υπάρχουν Λίστες</div>
                    </div>
                </div>
            </div>
        @else
            <div class="table-responsive">
                <table id="index_lists" class="table table-bordered table-hover" cellspacing="0" width="100%">
                    <thead>
                        <tr class="active">
                            <th class="text-center">Σχολική Μονάδα</th>
                            <th class="text-center">Σχ. Έτος</th>
                            <th class="text-center">Άθλημα</th>
                            <th class="text-center">Φύλο</th>
                            <th class="text-center">Κλειδωμένο</th>
                            <th class="text-center">Αρχείο</th>
                            <th class="text-center">Ημνια Δημιουργίας</th>
                            <th class="text-center">Προβολή</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach($lists as $list)
                            <tr>
                                <td>
                                    {!! $list->school->name !!}
                                </td>
                                <td class="text-center">{!! $list->year->name !!}</td>
                                <td>{!! $list->sport->name !!}</td>

                                <td class="text-center">
                                    @if($list->gender == 0)
                                        Κορίτσια
                                    @elseif($list->gender == 1)
                                        Αγόρια
                                    @else
                                        Μικτό
                                    @endif
                                <td class="text-center">
                                    @if($list->locked)
                                        <a href="{!! action('OFA\AdminOfaController@toggleLock', $list->id) !!}" class="btn btn-default btn-xs">
                                            <span style="color: #ff4d4d">
                                                <i class="fa fa-lock" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                    @else
                                        <a href="{!! action('OFA\AdminOfaController@toggleLock', $list->id) !!}" class="btn btn-default btn-xs">
                                            <span style="color: #008000">
                                                <i class="fa fa-unlock" aria-hidden="true"></i>
                                            </span>
                                        </a>
                                    @endif

                                </td>
                                <td class="text-center">
                                    @if($list->filename != null || $list->filename != '')
                                        <a href="{!! route('OFA::admin::downloadPdfListAdmin', [
                                           'year_name' => $list->year->name,
                                           'sport_name' => $list->sport->name,
                                           'gender'     => $list->gender,
                                           'school_name'    => str_replace(' ', '-', $list->school->name),
                                           'school_type'    => $list->school->type
                                        ]) !!}">
                                            <img height="30px" width="30px" src="{!! asset('img/download_icon.jpg') !!}"/>
                                        </a>
                                    @endif
                                </td>
                                <td class="text-center">
                                    {!! $list->updated_at !!}
                                </td>
                                <td class="text-center">
                                    <a href="{!! action('OFA\AdminOfaController@showList', Crypt::encrypt($list->id)) !!}">
                                        <img height="30px" width="30px" src="{!! asset('img/details-icon.png') !!}"/>
                                    </a>
                                </td>
                            </tr>
                        @endforeach

                    </tbody>
                </table>
            </div>

        @endif

resources/views/OFA/admin/_javascript.blade.php
<script>
    $(document).ready(function() {


        $('select').change(function(){
            var url = $(this).val();
            window.location = url;
        })
        .select2({
            placeholder: "Επιλογή Σχολείου",
            theme: "classic",
            language: {
                noResults: function() {
                    return "Δεν υπάρχει αποτέλεσμα αναζήτησης";
                }
            }
        });


        var table = $('#lists').DataTable({
                "order": [[ 2, "asc" ]],
                "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 3, 7, 8 ] } ],
                "language": {
                            "lengthMenu": "Προβολή _MENU_ εγγραφών ανά σελίδα",
                            "zeroRecords": "Δεν βρέθηκε καμία εγγραφή",
                            "info": "Προβολή σελίδας _PAGE_ από _PAGES_",
                            "infoEmpty": "Καμία εγγραφή διαθέσιμη",
                            "infoFiltered": "(φιλτράρισμα  από  _MAX_ συνολικές εγγραφές)",
                            "search": "Αναζήτηση:",
                            "paginate": {
                                  "previous": "Προηγούμενη",
                                  "next" : "Επόμενη"
                                }
                        }
        });

    });
</script>

resources/views/OFA/admin/all-lists-by-filter.blade.php
@extends('app')

@section('header.style')
    <link href="https://cdn.datatables.net/1.10.9/css/dataTables.bootstrap.min.css" rel="stylesheet">
@endsection

@section('scripts.footer')
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(document).ready(function() {

//
//            $('select').change(function(){
//                var url = $(this).val();
//                window.location = url;
//            })
//            .select2({
//                placeholder: "Επιλογή Σχολείου",
//                theme: "classic",
//                language: {
//                    noResults: function() {
//                        return "Δεν υπάρχει αποτέλεσμα αναζήτησης";
//                    }
//                }
//            });


            var table = $('#index_lists').DataTable({
                    "order": [[ 6, "asc" ]],
                    "aoColumnDefs": [ { "bSortable": false, "aTargets": [ 4,5,7 ] } ],
                    "language": {
                                "lengthMenu": "Προβολή _MENU_ εγγραφών ανά σελίδα",
                                "zeroRecords": "Δεν βρέθηκε καμία εγγραφή",
                                "info": "Προβολή σελίδας _PAGE_ από _PAGES_",
                                "infoEmpty": "Καμία εγγραφή διαθέσιμη",
                                "infoFiltered": "(φιλτράρισμα  από  _MAX_ συνολικές εγγραφές)",
                                "search": "Αναζήτηση:",
                                "paginate": {
                                      "previous": "Προηγούμενη",
                                      "next" : "Επόμενη"
                                    }
                            }
            });

        });
    </script>
@endsection

@section('title')
    Λίστες όλων των Σχολείων
@endsection

@section('content')
    <h2>
        Λίστες
    </h2>

    <div class="col-md-12 col-lg-12">
        @include('OFA.admin._index-lists-by-filter')
    </div>
@endsection

resources/views/OFA/admin/show-all-lists.blade.php
@extends('app')

@section('title')
    Προβολή Λίστας Συμμετοχής
@endsection

@section('scripts.footer')
	@include('OFA.admin._javascript')
@endsection

@section('content')
    <div class="col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Προβολή Λίστας Αγώνων
            </div>
            <div class="panel-body">
                <h3 class="text-center">

                <select size="30">
                    <option></option>
                    @foreach($schools as $school)
                        <option value="{!! action('OFA\AdminOfaController@showLists',str_replace(' ', '-', $school->name)) !!}"
                            {{--@if(str_replace(' ', '-', $name) == str_replace(' ', '-', $school))--}}
                                {{--selected--}}
                            {{--@endif--}}
                        >{!! $school->name !!}</option>
                    @endforeach
                </select>
                </h3>
            </div>
        </div>
    </div>
@endsection

resources/views/OFA/admin/show-school-list.blade.php
@extends('app')

@section('title')
    Λίστα Συμμετοχής για: {!! $name !!}
@endsection

@section('header.style')
    <link href="https://cdn.datatables.net/1.10.9/css/dataTables.bootstrap.min.css" rel="stylesheet">
@endsection

@section('scripts.footer')
    <script src="https://cdn.datatables.net/1.10.9/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.9/js/dataTables.bootstrap.min.js"></script>
	@include('OFA.admin._javascript')
@endsection

@section('content')
    <div class="col-md-12 col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                Λίστα Συμμετοχής για: {!! $name !!}
            </div>
            <div class="panel-body">
                <h3 class="text-center">

                <select size="40">
                    <option></option>
                    @foreach($schools as $school)
                        <option value="{!! action('OFA\AdminOfaController@showLists',str_replace(' ', '-', $school->name)) !!}"
                            @if(str_replace(' ', '-', $name) == str_replace(' ', '-', $school->name))
                                selected
                            @endif
                        >{!! $school->name !!}</option>
                    @endforeach
                </select>
                </h3>
            </div>
        </div>
    </div>

    <div class="col-md-12 col-lg-12">
        @include('OFA.school.tables._index-lists-table', ['name' => $name, 'school_id' => $school_id])
    </div>
@endsection